import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="mainifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
        <meta name="description" content={metadata.description ?? ''} />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
